# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fELfKPaGHT0_hlFdsleco5BtnjS0iBUo

Задание 1
"""

import re

car_id = input("Введите номер для проверки на валидность: ")

def val_num(car_id):
    pattern = re.compile(r'^[АВЕКМНОРСТУХ]\d{3}[АВЕКМНОРСТУХ]{2}(?P<reg>\d{2,3})$')
    match = pattern.match(car_id)
    if match:
        return f"Результат: Номер {car_id} валиден. Регион: {match['reg']}"
    else:
        return f"Результат: Номер {car_id} не валиден"
    
val_num(car_id)

"""Задание 2"""

some_string = 'Напишите функцию функцию, которая будет будет будет будет удалять все все все все последовательные повторы слов из из из из заданной строки строки при помощи регулярных выражений'

def del_repeats(some_string):
    pattern = r'(\w+)(\s+\1)+'
    return re.sub(pattern, r'\1', some_string)

del_repeats(some_string)